/*
 * This file was automatically generated by create-native-map from src/Fuse.NET/bin/Release/net5.0/Fuse.NET.dll.
 *
 * DO NOT MODIFY.
 */

using System;
using System.Runtime.InteropServices;
using Mono.Unix.Native;

namespace Mono.Unix.Native {

	public sealed /* static */ partial class NativeConvert
	{
		private NativeConvert () {}

		private const string LIB = "MonoFuseHelper";

		private static void ThrowArgumentException (object value)
		{
			throw new ArgumentOutOfRangeException ("value", value,
				Locale.GetText ("Current platform doesn't support this value."));
		}

		[DllImport (LIB, EntryPoint="Fuse_NET_FromArgs")]
		private static extern int FromArgs (Args source, IntPtr destination);

		public static bool TryCopy (Args source, IntPtr destination)
		{
			return FromArgs (source, destination) == 0;
		}

		[DllImport (LIB, EntryPoint="Fuse_NET_ToArgs")]
		private static extern int ToArgs (IntPtr source, Args destination);

		public static bool TryCopy (IntPtr source, Args destination)
		{
			return ToArgs (source, destination) == 0;
		}

	}
}

